import dayjs from 'dayjs';

/**
 * Formats date object to iCalendar UTC timestamp string: YYYYMMDDTHHMMSSZ
 */
function formatICSDate(dateStr, minutesOffset = 0) {
  const d = dayjs(dateStr).add(minutesOffset, 'minute');
  return d.format('YYYYMMDDTHHmm00');
}

/**
 * Generates an RFC 5545 compliant iCalendar (.ics) string for a plan's schedule
 */
export function generateICSContent(planTitle, schedule, availableMinutesPerDay = 120) {
  let ics = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Study Streak Rescue//Catch-Up Schedule//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${planTitle} Catch-Up Schedule`
  ];

  for (const day of schedule || []) {
    if (day.isBufferDay || !day.tasks || day.tasks.length === 0) continue;

    let currentStartTime = dayjs(day.date).hour(9).minute(0); // Default start 9:00 AM

    for (const t of day.tasks) {
      const startStr = currentStartTime.format('YYYYMMDDTHHmm00');
      const endTime = currentStartTime.add(t.estimatedMinutes || 30, 'minute');
      const endStr = endTime.format('YYYYMMDDTHHmm00');

      ics.push(
        'BEGIN:VEVENT',
        `UID:ssr_${t.taskId || Math.random().toString(36).substr(2, 9)}@studystreakrescue`,
        `DTSTAMP:${dayjs().format('YYYYMMDDTHHmm00')}Z`,
        `DTSTART:${startStr}`,
        `DTEND:${endStr}`,
        `SUMMARY:📚 ${t.title} (${planTitle})`,
        `DESCRIPTION:Scheduled study session for ${t.title}. Duration: ${t.estimatedMinutes} mins. Generated by Study Streak Rescue.`,
        'STATUS:CONFIRMED',
        'BEGIN:VALARM',
        'TRIGGER:-PT15M',
        'ACTION:DISPLAY',
        'DESCRIPTION:Study Reminder: ' + t.title,
        'END:VALARM',
        'END:VEVENT'
      );

      // Advance start time for next task on same day (+ 10 min break)
      currentStartTime = endTime.add(10, 'minute');
    }
  }

  ics.push('END:VCALENDAR');
  return ics.join('\r\n');
}

/**
 * Downloads the .ics file directly to the user's browser
 */
export function downloadICSFile(planTitle, schedule, availableMinutesPerDay) {
  const icsContent = generateICSContent(planTitle, schedule, availableMinutesPerDay);
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  const safeTitle = (planTitle || 'Catch_Up_Plan').replace(/[^a-zA-Z0-9_-]/g, '_');
  a.download = `${safeTitle}_Calendar_Sync.ics`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 100);
}

/**
 * Generates a direct Google Calendar web event creation link for a task
 */
export function getGoogleCalendarLink(taskTitle, dateStr, estimatedMinutes = 45, planTitle = 'Study Catch-Up') {
  const startTime = dayjs(dateStr).hour(9).minute(0);
  const endTime = startTime.add(estimatedMinutes, 'minute');

  const startIso = startTime.format('YYYYMMDDTHHmm00');
  const endIso = endTime.format('YYYYMMDDTHHmm00');

  const titleParam = encodeURIComponent(`📚 ${taskTitle} (${planTitle})`);
  const detailsParam = encodeURIComponent(`Study session: ${taskTitle}. Duration: ${estimatedMinutes} mins. Generated by Study Streak Rescue.`);

  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${titleParam}&dates=${startIso}/${endIso}&details=${detailsParam}`;
}
